name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }} # add concurrency
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "lint",
        ]
        include:
          - ci_step: "lint"
            command: make lint
            codecov: false

    runs-on: self-hosted
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout znet
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
